// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package com.hex.netty.protocol.pb.proto;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hex.netty.protocol.pb.proto.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 序列
     * </pre>
     *
     * <code>string seq = 1;</code>
     */
    java.lang.String getSeq();
    /**
     * <pre>
     * 序列
     * </pre>
     *
     * <code>string seq = 1;</code>
     */
    com.google.protobuf.ByteString
        getSeqBytes();

    /**
     * <pre>
     * 指令，用于服务端分发请求，类似http url
     * </pre>
     *
     * <code>string cmd = 2;</code>
     */
    java.lang.String getCmd();
    /**
     * <pre>
     * 指令，用于服务端分发请求，类似http url
     * </pre>
     *
     * <code>string cmd = 2;</code>
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <pre>
     * 指令类型，0=心跳，1=请求，2=响应
     * </pre>
     *
     * <code>int32 commandType = 3;</code>
     */
    int getCommandType();

    /**
     * <pre>
     * 结果码，作为response时才具备
     * </pre>
     *
     * <code>int32 code = 4;</code>
     */
    int getCode();

    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 ts = 5;</code>
     */
    long getTs();

    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string body = 6;</code>
     */
    java.lang.String getBody();
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string body = 6;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * Protobuf type {@code com.hex.netty.protocol.pb.proto.Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hex.netty.protocol.pb.proto.Packet)
      PacketOrBuilder {
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      seq_ = "";
      cmd_ = "";
      commandType_ = 0;
      code_ = 0;
      ts_ = 0L;
      body_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              seq_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cmd_ = s;
              break;
            }
            case 24: {

              commandType_ = input.readInt32();
              break;
            }
            case 32: {

              code_ = input.readInt32();
              break;
            }
            case 40: {

              ts_ = input.readInt64();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hex.netty.protocol.pb.proto.Rpc.internal_static_com_hex_netty_protocol_pb_proto_Packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hex.netty.protocol.pb.proto.Rpc.internal_static_com_hex_netty_protocol_pb_proto_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hex.netty.protocol.pb.proto.Rpc.Packet.class, com.hex.netty.protocol.pb.proto.Rpc.Packet.Builder.class);
    }

    public static final int SEQ_FIELD_NUMBER = 1;
    private volatile java.lang.Object seq_;
    /**
     * <pre>
     * 序列
     * </pre>
     *
     * <code>string seq = 1;</code>
     */
    public java.lang.String getSeq() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seq_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 序列
     * </pre>
     *
     * <code>string seq = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSeqBytes() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private volatile java.lang.Object cmd_;
    /**
     * <pre>
     * 指令，用于服务端分发请求，类似http url
     * </pre>
     *
     * <code>string cmd = 2;</code>
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 指令，用于服务端分发请求，类似http url
     * </pre>
     *
     * <code>string cmd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMANDTYPE_FIELD_NUMBER = 3;
    private int commandType_;
    /**
     * <pre>
     * 指令类型，0=心跳，1=请求，2=响应
     * </pre>
     *
     * <code>int32 commandType = 3;</code>
     */
    public int getCommandType() {
      return commandType_;
    }

    public static final int CODE_FIELD_NUMBER = 4;
    private int code_;
    /**
     * <pre>
     * 结果码，作为response时才具备
     * </pre>
     *
     * <code>int32 code = 4;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int TS_FIELD_NUMBER = 5;
    private long ts_;
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 ts = 5;</code>
     */
    public long getTs() {
      return ts_;
    }

    public static final int BODY_FIELD_NUMBER = 6;
    private volatile java.lang.Object body_;
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string body = 6;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string body = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSeqBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, seq_);
      }
      if (!getCmdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cmd_);
      }
      if (commandType_ != 0) {
        output.writeInt32(3, commandType_);
      }
      if (code_ != 0) {
        output.writeInt32(4, code_);
      }
      if (ts_ != 0L) {
        output.writeInt64(5, ts_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, body_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSeqBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, seq_);
      }
      if (!getCmdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cmd_);
      }
      if (commandType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, commandType_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, code_);
      }
      if (ts_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, ts_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, body_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hex.netty.protocol.pb.proto.Rpc.Packet)) {
        return super.equals(obj);
      }
      com.hex.netty.protocol.pb.proto.Rpc.Packet other = (com.hex.netty.protocol.pb.proto.Rpc.Packet) obj;

      boolean result = true;
      result = result && getSeq()
          .equals(other.getSeq());
      result = result && getCmd()
          .equals(other.getCmd());
      result = result && (getCommandType()
          == other.getCommandType());
      result = result && (getCode()
          == other.getCode());
      result = result && (getTs()
          == other.getTs());
      result = result && getBody()
          .equals(other.getBody());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + COMMANDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCommandType();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + TS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTs());
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hex.netty.protocol.pb.proto.Rpc.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hex.netty.protocol.pb.proto.Rpc.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hex.netty.protocol.pb.proto.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hex.netty.protocol.pb.proto.Packet)
        com.hex.netty.protocol.pb.proto.Rpc.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hex.netty.protocol.pb.proto.Rpc.internal_static_com_hex_netty_protocol_pb_proto_Packet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hex.netty.protocol.pb.proto.Rpc.internal_static_com_hex_netty_protocol_pb_proto_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hex.netty.protocol.pb.proto.Rpc.Packet.class, com.hex.netty.protocol.pb.proto.Rpc.Packet.Builder.class);
      }

      // Construct using com.hex.netty.protocol.pb.proto.Rpc.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        seq_ = "";

        cmd_ = "";

        commandType_ = 0;

        code_ = 0;

        ts_ = 0L;

        body_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hex.netty.protocol.pb.proto.Rpc.internal_static_com_hex_netty_protocol_pb_proto_Packet_descriptor;
      }

      public com.hex.netty.protocol.pb.proto.Rpc.Packet getDefaultInstanceForType() {
        return com.hex.netty.protocol.pb.proto.Rpc.Packet.getDefaultInstance();
      }

      public com.hex.netty.protocol.pb.proto.Rpc.Packet build() {
        com.hex.netty.protocol.pb.proto.Rpc.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hex.netty.protocol.pb.proto.Rpc.Packet buildPartial() {
        com.hex.netty.protocol.pb.proto.Rpc.Packet result = new com.hex.netty.protocol.pb.proto.Rpc.Packet(this);
        result.seq_ = seq_;
        result.cmd_ = cmd_;
        result.commandType_ = commandType_;
        result.code_ = code_;
        result.ts_ = ts_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hex.netty.protocol.pb.proto.Rpc.Packet) {
          return mergeFrom((com.hex.netty.protocol.pb.proto.Rpc.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hex.netty.protocol.pb.proto.Rpc.Packet other) {
        if (other == com.hex.netty.protocol.pb.proto.Rpc.Packet.getDefaultInstance()) return this;
        if (!other.getSeq().isEmpty()) {
          seq_ = other.seq_;
          onChanged();
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          onChanged();
        }
        if (other.getCommandType() != 0) {
          setCommandType(other.getCommandType());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.getTs() != 0L) {
          setTs(other.getTs());
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hex.netty.protocol.pb.proto.Rpc.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hex.netty.protocol.pb.proto.Rpc.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object seq_ = "";
      /**
       * <pre>
       * 序列
       * </pre>
       *
       * <code>string seq = 1;</code>
       */
      public java.lang.String getSeq() {
        java.lang.Object ref = seq_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          seq_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 序列
       * </pre>
       *
       * <code>string seq = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSeqBytes() {
        java.lang.Object ref = seq_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          seq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 序列
       * </pre>
       *
       * <code>string seq = 1;</code>
       */
      public Builder setSeq(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 序列
       * </pre>
       *
       * <code>string seq = 1;</code>
       */
      public Builder clearSeq() {
        
        seq_ = getDefaultInstance().getSeq();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 序列
       * </pre>
       *
       * <code>string seq = 1;</code>
       */
      public Builder setSeqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        seq_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <pre>
       * 指令，用于服务端分发请求，类似http url
       * </pre>
       *
       * <code>string cmd = 2;</code>
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 指令，用于服务端分发请求，类似http url
       * </pre>
       *
       * <code>string cmd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 指令，用于服务端分发请求，类似http url
       * </pre>
       *
       * <code>string cmd = 2;</code>
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 指令，用于服务端分发请求，类似http url
       * </pre>
       *
       * <code>string cmd = 2;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 指令，用于服务端分发请求，类似http url
       * </pre>
       *
       * <code>string cmd = 2;</code>
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cmd_ = value;
        onChanged();
        return this;
      }

      private int commandType_ ;
      /**
       * <pre>
       * 指令类型，0=心跳，1=请求，2=响应
       * </pre>
       *
       * <code>int32 commandType = 3;</code>
       */
      public int getCommandType() {
        return commandType_;
      }
      /**
       * <pre>
       * 指令类型，0=心跳，1=请求，2=响应
       * </pre>
       *
       * <code>int32 commandType = 3;</code>
       */
      public Builder setCommandType(int value) {
        
        commandType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 指令类型，0=心跳，1=请求，2=响应
       * </pre>
       *
       * <code>int32 commandType = 3;</code>
       */
      public Builder clearCommandType() {
        
        commandType_ = 0;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       * 结果码，作为response时才具备
       * </pre>
       *
       * <code>int32 code = 4;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 结果码，作为response时才具备
       * </pre>
       *
       * <code>int32 code = 4;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 结果码，作为response时才具备
       * </pre>
       *
       * <code>int32 code = 4;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private long ts_ ;
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 ts = 5;</code>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 ts = 5;</code>
       */
      public Builder setTs(long value) {
        
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 ts = 5;</code>
       */
      public Builder clearTs() {
        
        ts_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string body = 6;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string body = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string body = 6;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string body = 6;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string body = 6;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.hex.netty.protocol.pb.proto.Packet)
    }

    // @@protoc_insertion_point(class_scope:com.hex.netty.protocol.pb.proto.Packet)
    private static final com.hex.netty.protocol.pb.proto.Rpc.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hex.netty.protocol.pb.proto.Rpc.Packet();
    }

    public static com.hex.netty.protocol.pb.proto.Rpc.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    public com.hex.netty.protocol.pb.proto.Rpc.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ErrOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hex.netty.protocol.pb.proto.Err)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>string key = 2;</code>
     */
    java.lang.String getKey();
    /**
     * <code>string key = 2;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();
  }
  /**
   * Protobuf type {@code com.hex.netty.protocol.pb.proto.Err}
   */
  public  static final class Err extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hex.netty.protocol.pb.proto.Err)
      ErrOrBuilder {
    // Use Err.newBuilder() to construct.
    private Err(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Err() {
      code_ = 0;
      key_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Err(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hex.netty.protocol.pb.proto.Rpc.internal_static_com_hex_netty_protocol_pb_proto_Err_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hex.netty.protocol.pb.proto.Rpc.internal_static_com_hex_netty_protocol_pb_proto_Err_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hex.netty.protocol.pb.proto.Rpc.Err.class, com.hex.netty.protocol.pb.proto.Rpc.Err.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 2;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hex.netty.protocol.pb.proto.Rpc.Err)) {
        return super.equals(obj);
      }
      com.hex.netty.protocol.pb.proto.Rpc.Err other = (com.hex.netty.protocol.pb.proto.Rpc.Err) obj;

      boolean result = true;
      result = result && (getCode()
          == other.getCode());
      result = result && getKey()
          .equals(other.getKey());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hex.netty.protocol.pb.proto.Rpc.Err parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Err parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Err parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Err parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Err parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Err parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Err parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Err parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Err parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hex.netty.protocol.pb.proto.Rpc.Err parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hex.netty.protocol.pb.proto.Rpc.Err prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hex.netty.protocol.pb.proto.Err}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hex.netty.protocol.pb.proto.Err)
        com.hex.netty.protocol.pb.proto.Rpc.ErrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hex.netty.protocol.pb.proto.Rpc.internal_static_com_hex_netty_protocol_pb_proto_Err_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hex.netty.protocol.pb.proto.Rpc.internal_static_com_hex_netty_protocol_pb_proto_Err_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hex.netty.protocol.pb.proto.Rpc.Err.class, com.hex.netty.protocol.pb.proto.Rpc.Err.Builder.class);
      }

      // Construct using com.hex.netty.protocol.pb.proto.Rpc.Err.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 0;

        key_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hex.netty.protocol.pb.proto.Rpc.internal_static_com_hex_netty_protocol_pb_proto_Err_descriptor;
      }

      public com.hex.netty.protocol.pb.proto.Rpc.Err getDefaultInstanceForType() {
        return com.hex.netty.protocol.pb.proto.Rpc.Err.getDefaultInstance();
      }

      public com.hex.netty.protocol.pb.proto.Rpc.Err build() {
        com.hex.netty.protocol.pb.proto.Rpc.Err result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hex.netty.protocol.pb.proto.Rpc.Err buildPartial() {
        com.hex.netty.protocol.pb.proto.Rpc.Err result = new com.hex.netty.protocol.pb.proto.Rpc.Err(this);
        result.code_ = code_;
        result.key_ = key_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hex.netty.protocol.pb.proto.Rpc.Err) {
          return mergeFrom((com.hex.netty.protocol.pb.proto.Rpc.Err)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hex.netty.protocol.pb.proto.Rpc.Err other) {
        if (other == com.hex.netty.protocol.pb.proto.Rpc.Err.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hex.netty.protocol.pb.proto.Rpc.Err parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hex.netty.protocol.pb.proto.Rpc.Err) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 2;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.hex.netty.protocol.pb.proto.Err)
    }

    // @@protoc_insertion_point(class_scope:com.hex.netty.protocol.pb.proto.Err)
    private static final com.hex.netty.protocol.pb.proto.Rpc.Err DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hex.netty.protocol.pb.proto.Rpc.Err();
    }

    public static com.hex.netty.protocol.pb.proto.Rpc.Err getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Err>
        PARSER = new com.google.protobuf.AbstractParser<Err>() {
      public Err parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Err(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Err> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Err> getParserForType() {
      return PARSER;
    }

    public com.hex.netty.protocol.pb.proto.Rpc.Err getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hex_netty_protocol_pb_proto_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hex_netty_protocol_pb_proto_Packet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hex_netty_protocol_pb_proto_Err_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hex_netty_protocol_pb_proto_Err_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tRpc.proto\022\037com.hex.netty.protocol.pb.p" +
      "roto\"_\n\006Packet\022\013\n\003seq\030\001 \001(\t\022\013\n\003cmd\030\002 \001(\t" +
      "\022\023\n\013commandType\030\003 \001(\005\022\014\n\004code\030\004 \001(\005\022\n\n\002t" +
      "s\030\005 \001(\003\022\014\n\004body\030\006 \001(\t\" \n\003Err\022\014\n\004code\030\001 \001" +
      "(\005\022\013\n\003key\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hex_netty_protocol_pb_proto_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hex_netty_protocol_pb_proto_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hex_netty_protocol_pb_proto_Packet_descriptor,
        new java.lang.String[] { "Seq", "Cmd", "CommandType", "Code", "Ts", "Body", });
    internal_static_com_hex_netty_protocol_pb_proto_Err_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hex_netty_protocol_pb_proto_Err_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hex_netty_protocol_pb_proto_Err_descriptor,
        new java.lang.String[] { "Code", "Key", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
